import assert from 'node:assert/strict';
import fs from 'node:fs';
import {filterBuildings,scenario,csvText,sortRows,describe} from '../dist/analytics.js';
const data=JSON.parse(fs.readFileSync(new URL('../dist/data/buildings.json',import.meta.url)));
const blank={type:'all',min:'',max:'',zip:'',status:'',query:''};
const all=filterBuildings(data,blank);assert.equal(all.length,5034);
const before=JSON.stringify(data);
assert.equal(scenario(all,0).kbtu,0);
const full=scenario(all,1),half=scenario(all,.5);
assert.equal(half.kbtu,full.kbtu*.5);assert.equal(full.n,2647);
assert.deepEqual(scenario([],1),{n:0,above:0,kbtu:null});
assert.equal(scenario(data.filter(r=>!r.comparison_eligible),0).kbtu,null);
for(const bad of [-1,1.1,NaN,Infinity])assert.throws(()=>scenario(all,bad));
const id='100933',r=data.find(r=>r.id===id);
const selected=filterBuildings(data,{...blank,query:id});assert.equal(selected.length,1);
assert.equal(selected[0].peer_median,r.peer_median);assert.equal(selected[0].peer_n,841);
const mf=filterBuildings(data,{...blank,type:'Multifamily Housing',min:'25000',max:'50000'});
assert.ok(mf.length>0&&mf.every(r=>r.area>=25000&&r.area<=50000));
const zip=filterBuildings(data,{...blank,zip:'02127',status:'in compliance'});assert.ok(zip.every(r=>r.zip==='02127'&&r.status==='in compliance'));
assert.equal(filterBuildings(data,{...blank,query:'zzzz-nonexistent'}).length,0);
assert.equal(filterBuildings(data,{...blank,min:'50000',max:'100'}).length,0);
assert.equal(JSON.stringify(data),before,'Filters/scenarios cannot mutate fixed benchmarks');
assert.equal(csvText([],0).split('\r\n').length,1,'Empty export has headers only');
assert.ok(csvText(selected,.5).includes('selected_gap_closure_fraction'));
assert.ok(csvText(selected,.5).includes(String(r.full_gap_kbtu*.5)));
const sorted=sortRows(selected,'calculated_eui','asc');assert.equal(sorted[0].id,id);
assert.equal(describe(selected).median,r.calculated_eui);
assert.equal(describe([]).median,null);
console.log('PASS: actual-data filters, fixed benchmarks, 0% / 50% / 100% / empty scenarios, invalid fraction rejection, CSV scenario fields, empty CSV, sorting and distributions.');
