"""Create English course deliverables from the generated analysis, not copied statistics."""
from pathlib import Path
import json, html
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.colors import HexColor
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import letter
from pypdf import PdfReader
ROOT=Path(__file__).resolve().parents[1];DIST=ROOT/'dist';OUT=DIST/'deliverables';OUT.mkdir(exist_ok=True)
m=json.loads((DIST/'data/metadata.json').read_text());b=json.loads((DIST/'data/buildings.json').read_text())
f=lambda n,d=0:f'{n:,.{d}f}'
mf=next(t for t in m['type_stats'] if t['type']=='Multifamily Housing');of=next(t for t in m['type_stats'] if t['type']=='Office')
example=max((r for r in b if r['investigation_candidate'] and r['type']=='Multifamily Housing' and not r['review_required']),key=lambda r:r['relative_to_peer'])
sections=[
('Source and period',f"The supplied {m['source_file']} is the sole analytical input. Analyze Boston labels it a 2025 disclosure release. Energy-use year is not independently confirmed. Boston's general reporting guidance suggests prior-calendar-year data, but the resource does not explicitly confirm this file's period. The resource page was created {m['official_resource_created']} and updated {m['official_resource_updated']}. Original download date: unknown. Processing: {m['processed_at'][:10]} UTC."),
('Scope and deduplication',f"The workbook contains {f(m['buildings_n'])} unique building IDs: {f(m['non_campus_n'])} non-campus buildings and {f(m['campus_members_n'])} campus members. There are {m['campus_summaries_n']} campus summaries. Headers and identifier patterns locate sections; {m['duplicate_records_removed']} duplicate appearances are removed. The campus worksheet wins duplicate summaries/members; shared fields agree after numeric normalization. The Summary's claim that campuses were removed from the main sheet is contradicted by its contents. Campus lists reference two absent building IDs (104716, 107224)."),
('Cleaning and quality',"Original values, source sheet/row, normalized fields and value states remain in public analysis exports, excluding owner names and free-text notes. Missing, #N/A, zero, negative and unparseable values stay distinct. Verified Excel formats restore identifier zeros. Parcel addresses are labeled fallbacks. Unresolved energy-input problems exclude records from energy comparisons; water/emissions issues are separate. Water intensity above 1,000 gallons/ft²/year triggers review. Missing ENERGY STAR scores do not automatically imply reporting failure."),
('Metrics and checks',"Calculated Site EUI = total site energy (kBtu) / reported gross floor area (ft², excluding parking). Numerator must be nonnegative; denominator positive. Reported EUI stays separate. Absolute difference >0.11 kBtu/ft² excludes unresolved cases. Negative/unparseable energy components or a component exceeding total by max(1 kBtu, 0.01%) also trigger energy review. Electricity converts at 3.412141633 kBtu/kWh only for that check. Onsite renewables are already included in electricity and are not added again. Emissions use kgCO₂e; divide by 1,000 for tons. Emissions intensity uses area including enclosed parking. Observed component sums are checked at max(0.01 kg, 0.0001% of total) tolerance; missing components remain unknown."),
('Peers, rankings and scenario',f"Fixed peers match primary use and area bands: <25k, 25–<50k, 50–<100k, 100–<250k and ≥250k ft². The positive-area median is {f(m['area_distribution']['median'])} ft². {f(m['energy_eligible_n'])} records pass energy checks; {f(m['comparison_eligible_n'])} have groups of at least 20, a display rule rather than statistical assurance. Quartiles use linear interpolation. Candidates exceed their peer 75th percentile; filters never change benchmarks. Scenario difference = max(0, calculated EUI − peer median) × area × closure fraction (0–1; default 0.5). Only comparison-eligible non-campus records qualify. This illustrates a benchmark gap, not engineering savings."),
('Coverage, aggregation and limits',f"{f(m['reported_eui_numeric_n'])}/{f(m['non_campus_n'])} non-campus records have numeric reported EUI (pre-screen median {m['reported_eui_preclean_median']} kBtu/ft²). Aggregates use {f(m['aggregate_entities_n'])} entities: non-campus buildings + one summary per campus; never members as well. Reported sums are disclosure values, not citywide totals. Missingness and selection affect results. One release cannot show trends or policy effects. Use/size matching does not control operations; correlations are not causal. Estimated emissions do not establish final compliance. Costs, prices, occupancy, hours, age and equipment performance are unavailable or insufficient.")]
def shell(title,body,extra=''):
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title} · Boston Building Energy Explorer</title><link rel="icon" href="favicon.svg"><link rel="stylesheet" href="style.css">{extra}</head><body><header><a class="brand" href="index.html#explore">BOSTON <small>BUILDING ENERGY EXPLORER</small></a><a href="index.html#methods">← Data & methods</a></header><main><div class="prose">{body}</div></main><footer>Boston Building Energy Explorer · Independent course project</footer></body></html>'''
sources=f'<p class="note">Sources: <a href="{m["source_url"]}">Analyze Boston disclosure resource</a>; <a href="{m["official_context_url"]}">Boston BERDO reporting and publication guidance</a>. The supplied workbook and its Data Dictionary are the analytical source.</p>'
methodbody='<p class="eyebrow">Course deliverable 02</p><h1>Data & methodology</h1><p class="subtitle">A one-page note for interpreting the explorer.</p><p class="no-print"><a class="button primary" href="deliverables/methodology.pdf">Download the one-page PDF ↓</a></p>'+''.join(f'<h3>{title}</h3><p>{html.escape(body)}</p>' for title,body in sections)+sources
(DIST/'methodology.html').write_text(shell('Data & methodology',methodbody))
styles={
 'title':ParagraphStyle('title',fontName='Times-Roman',fontSize=24,leading=26,textColor=HexColor('#164e3e'),spaceAfter=5),
 'sub':ParagraphStyle('sub',fontName='Helvetica',fontSize=9,leading=12,textColor=HexColor('#536257'),spaceAfter=10),
 'head':ParagraphStyle('head',fontName='Helvetica-Bold',fontSize=9.1,leading=11,spaceBefore=6,spaceAfter=2,textColor=HexColor('#164e3e')),
 'body':ParagraphStyle('body',fontName='Helvetica',fontSize=9.5,leading=12.5,spaceAfter=2),
 'source':ParagraphStyle('source',fontName='Helvetica',fontSize=7.6,leading=9.5,spaceBefore=7,textColor=HexColor('#536257'))}
def pdftext(s):return html.escape(s.replace('–','-').replace('−','-').replace('≥','>=')).replace('²','<super>2</super>').replace('₂','<sub>2</sub>')
story=[Paragraph('Boston Building Energy Explorer',styles['title']),Paragraph('DATA & METHODOLOGY  /  2025 disclosure release; energy-use year unconfirmed',styles['sub'])]
for title,body in sections:story.extend([Paragraph(title,styles['head']),Paragraph(pdftext(body),styles['body'])])
story.append(Paragraph(f'Sources: <link href="{m["source_url"]}" color="#164e3e">Analyze Boston disclosure resource</link>; <link href="{m["official_context_url"]}" color="#164e3e">Boston BERDO guidance</link>. Workbook SHA-256: {m["source_sha256"]}',styles['source']))
def footer(c,doc):c.setFont('Helvetica',8);c.setFillColor(HexColor('#536257'));c.drawString(42,27,'Independent course project | Reported data supports investigation, not causal or compliance claims.');c.drawRightString(570,27,'1 / 1')
SimpleDocTemplate(str(OUT/'methodology.pdf'),pagesize=letter,leftMargin=42,rightMargin=42,topMargin=35,bottomMargin=42).build(story,onFirstPage=footer,onLaterPages=footer)
assert len(PdfReader(OUT/'methodology.pdf').pages)==1,'Methodology must fit one page'
reflection=[
('A useful screening tool',f"This project turns a difficult disclosure workbook into a transparent first step for investigation. The most consequential work was defining record grain. Without deduplication, campus summaries and their members could be counted together and buildings with shared meters could receive misleading rankings. The analysis retains {f(m['non_campus_n'])} non-campus records, including records with missing or questionable values, while eligibility rules select the reference population separately."),
('What the data supports',f"The disclosure supports descriptions of recorded energy intensity, reporting coverage and differences among buildings with similar primary uses and broad floor-area bands. It identifies {f(m['investigation_candidates_n'])} buildings above their eligible peer group's upper quartile. These are candidates for questions about meter boundaries, operations, occupancy and equipment. Missing inputs and explicit anomalies support a separate data-review workflow. The scenario lets a visitor understand the arithmetic size of a peer gap without treating it as a promised outcome."),
('What it cannot prove',"A single disclosure release does not establish annual trends or policy effects. Correlation between building characteristics and energy intensity does not establish causal effects of equipment or energy measures. Operating hours, building age, occupancy, equipment efficiency, retrofit costs and energy prices are unavailable or insufficient for causal or investment analysis. Even within the same property type and size band, operational differences and mixed uses remain. High EUI alone does not demonstrate poor management."),
('Uncertainty remains visible',"Missingness, reporting quality and sample selection affect interpretation. Eligible buildings may systematically differ from excluded ones. A minimum of 20 peers avoids the smallest comparison groups but does not establish representativeness or statistical significance. Estimated emissions do not establish final emissions compliance, particularly where renewable-energy treatment, custom emissions factors and flexibility measures are absent. A peer-benchmark scenario is not an engineering savings estimate and cannot justify claimed emissions reductions, financial returns or payback."),
('What should happen next',"For a selected energy candidate, verify the floor area and meter boundary, request operating schedules and occupancy information, and then consider an engineering assessment. For a review case, reconcile the original submission before interpreting its rank. A future evaluation of trends or policy would require harmonized multiple-year data and a credible comparison design. This release's energy-use year still needs explicit confirmation from the publisher. The practical contribution is a reproducible, inspectable decision aid with visible uncertainty.")]
reflectionbody='<p class="eyebrow">Course deliverable 04</p><h1>What this data can tell us</h1><p class="subtitle">A reflection on evidence, uncertainty and responsible comparison.</p>'+''.join(f'<h2>{t}</h2><p>{html.escape(p)}</p>' for t,p in reflection)+sources
(DIST/'reflection.html').write_text(shell('Reflection',reflectionbody))
(OUT/'reflection.md').write_text('# What this data can tell us\n\n'+'\n\n'.join('## '+t+'\n\n'+p for t,p in reflection))
slides=[
{'time':'0:00–0:40','title':'Which buildings need a closer look?','body':f'<p class="slide-lead">Compare similar buildings.<br>Separate energy investigation from data review.</p><p>For Boston planners, building managers and community sustainability organizations.</p><p class="note">{m["period_label"]}</p>','notes':"Our decision problem is practical: among buildings with similar uses and sizes, which warrant an energy-efficiency investigation, and which records need a data-quality review first? The explorer serves planners, managers and community sustainability organizations. High energy intensity is a reason to ask questions. It does not demonstrate poor management. We use the 2025 disclosure release, but the energy-use year remains unconfirmed, so this presentation does not label it as 2025 consumption."},
{'time':'0:40–1:25','title':'Three populations, three purposes','body':f'<table><tr><th>Scope</th><th>Count</th><th>Purpose</th></tr><tr><td>Unique building IDs</td><td>{f(m["buildings_n"])}</td><td>Coverage and relationships</td></tr><tr><td>Non-campus buildings</td><td>{f(m["non_campus_n"])}</td><td>Individual comparisons</td></tr><tr><td>Non-campus + campus summaries</td><td>{f(m["aggregate_entities_n"])} entities</td><td>Deduplicated aggregates</td></tr></table><p>{m["campus_summaries_n"]} campuses; {m["campus_members_n"]} recorded members. Two member references have no building record.</p>','notes':f"The workbook required more than joining two sheets. The Summary says campus data was removed from the main sheet, but actual rows contradict that statement. We identified sections by headers and IDs and removed {m['duplicate_records_removed']} repeated appearances. There are {f(m['buildings_n'])} unique building IDs, but only {f(m['non_campus_n'])} are non-campus buildings. Aggregate energy uses those buildings plus one summary per campus, never campus members as well. Two campus references point to absent building records. The website discloses that mismatch."},
{'time':'1:25–2:15','title':'Live exploration with a fixed benchmark','body':'<p class="slide-lead">Multifamily Housing → floor area → ZIP → building details</p><p>The distribution, scatterplot and table follow the same selection. Peer medians stay fixed.</p><a class="button primary" href="index.html#explore" target="_blank">Open the live explorer ↗</a><p class="note">Demo: choose Multifamily Housing, set minimum area to 25,000 and maximum to 50,000 ft², inspect a row, then reset.</p>','notes':"I will demonstrate the live filters now. Choose Multifamily Housing, then a floor-area range from 25,000 to 50,000 square feet. The selected count, distribution, scatterplot and table update together. Select a ZIP if useful, then open a building. Notice that the peer median and sample size are fixed to the full eligible release, not recalculated from the visible subset. Reset returns the initial focus. Missing and flagged records remain searchable in the table even when they cannot enter the energy chart. The log scatterplot reports how many records it excludes."},
{'time':'2:15–3:10','title':f'An investigation example: BERDO {example["id"]}','body':f'<p>{html.escape(example["address"])}<br>{f(example["area"])} ft² · Multifamily Housing</p><p class="slide-lead">{f(example["calculated_eui"],1)} vs. {f(example["peer_median"],1)} kBtu/ft²/year</p><p>Calculated Site EUI vs. fixed peer median<br>Under 25,000 ft² · n={example["peer_n"]} · {f(example["relative_to_peer"],2)}× median</p><p>50% benchmark scenario energy difference: <strong>{f(example["full_gap_kbtu"]*.5)} kBtu</strong></p><p class="note">Illustrative comparison. Verify area, metering and operating conditions before inferring an intervention.</p>','notes':f"This is BERDO {example['id']}, a multifamily building with a reported area of {f(example['area'])} square feet. Its calculated EUI is {f(example['calculated_eui'],1)}, compared with {f(example['peer_median'],1)} for its {example['peer_n']} eligible peers. It exceeds the upper quartile and passes the project energy checks. At 50 percent gap closure, the benchmark scenario difference is {f(example['full_gap_kbtu']*.5)} kBtu. This is arithmetic, not verified savings. A small reported area and unusual operations could help explain the result. The next step is to confirm the floor area, meter boundary and occupancy, then assess whether an engineering study is warranted."},
{'time':'3:10–4:10','title':'Findings support different next actions','body':f'<ol><li>{f(m["energy_eligible_n"]/m["non_campus_n"]*100,1)}% pass energy input checks. Missing inputs remain a major limitation.</li><li>Eligible multifamily median: {f(mf["median"],1)} (n={f(mf["n"])}). Office: {f(of["median"],1)} (n={f(of["n"])}), in kBtu/ft²/year.</li><li>{f(m["investigation_candidates_n"])} buildings exceed their eligible peer upper quartile.</li></ol><p><strong>Next actions:</strong> verify operating context for candidates; reconcile missing and inconsistent submissions for review cases.</p>','notes':f"Three observations support action. First, only {f(m['energy_eligible_n']/m['non_campus_n']*100,1)} percent of non-campus records pass the energy-input rules; missing energy is the largest exclusion reason. That supports an effort to complete and reconcile submissions. Second, even the focus categories have broad EUI distributions. Their category medians are descriptive, not evidence that one use is inherently inefficient. Third, {m['investigation_candidates_n']} buildings exceed their matched peer upper quartile. That supports collecting operating information for a focused investigation list. Separately, the negative electricity values at 102879 and 105219 require source review. Unrelated water and emissions flags do not automatically invalidate an energy comparison."},
{'time':'4:10–5:00','title':'A decision aid with explicit limits','body':'<p class="slide-lead">A peer gap is a question.<br>An audit must establish the answer.</p><ul><li>One release cannot establish trends or policy effects.</li><li>Use and size do not control all operational differences.</li><li>Missingness and selection affect comparisons.</li><li>Estimated emissions do not establish final compliance.</li><li>The scenario cannot promise savings or payback.</li></ul><a href="index.html#methods">Explore the data, methodology and reflection ↗</a>','notes':"This release does not establish trends or the effect of BERDO policy. Correlation cannot identify the causal effect of equipment or energy measures. We lack sufficient hours, occupancy, age, equipment performance, retrofit cost and energy-price information. Estimated emissions also do not determine final compliance. The contribution is narrower and useful: an inspectable way to separate questions about energy from questions about data, while keeping the reference population and formulas consistent. All analysis downloads, the methodology note and reflection are linked on the Data and Methods page. A real audit and corrected source data should guide any investment decision."}]
slidehtml=''.join(f'<section class="slide" id="slide-{i+1}" aria-label="Slide {i+1} of {len(slides)}" {"" if i==0 else "hidden"}><p class="eyebrow">{i+1:02d} / {len(slides):02d} · {s["time"]}</p><h1>{s["title"]}</h1><div class="slide-content">{s["body"]}</div><details class="speaker"><summary>English speaking outline · {s["time"]}</summary><p>{s["notes"]}</p></details><p class="note">Source: supplied workbook, reproducible analysis · Processed {m["processed_at"][:10]}</p></section>' for i,s in enumerate(slides))
presentation=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Five-minute presentation · Boston Building Energy Explorer</title><link rel="icon" href="favicon.svg"><link rel="stylesheet" href="style.css"><style>main{{max-width:1150px}}.slide{{min-height:65vh}}.slide h1{{font-size:clamp(35px,5vw,62px);margin-bottom:30px}}.slide-lead{{font-family:Georgia,serif;font-size:clamp(24px,3.5vw,40px);line-height:1.3}}.slide-content p,.slide-content li{{font-size:21px;line-height:1.6}}.slide li{{margin-bottom:14px}}.slide .note{{font-size:12px}}.speaker{{margin-top:30px}}.speaker p{{font-size:16px}}.slide table{{font-size:18px;margin:25px 0}}.slide[hidden]{{display:none}}@media print{{.slide[hidden]{{display:block}}.slide{{break-after:page;min-height:0}}.speaker,.slide-controls{{display:none}}.slide:last-of-type{{break-after:auto}}}}</style></head><body><header><a class="brand" href="index.html#explore">BOSTON <small>BUILDING ENERGY EXPLORER</small></a><a href="index.html#methods">← Course deliverables</a></header><main>{slidehtml}<div class="pagination slide-controls"><span id="slide-count">1 / 6 · Total 5:00</span><div><button id="back">← Previous</button><button id="forward" class="primary">Next →</button></div></div><p class="note no-print"><a href="deliverables/speaking-outline.md" download>Download the English speaking outline ↓</a> · Arrow keys navigate. Browser print includes all six slides.</p></main><script>let i=0;const slides=[...document.querySelectorAll('.slide')];function show(n){{i=Math.max(0,Math.min(slides.length-1,n));slides.forEach((s,j)=>s.hidden=j!==i);document.querySelector('#slide-count').textContent=(i+1)+' / '+slides.length+' · Total 5:00';document.querySelector('#back').disabled=i===0;document.querySelector('#forward').disabled=i===slides.length-1;}}document.querySelector('#back').onclick=()=>show(i-1);document.querySelector('#forward').onclick=()=>show(i+1);document.addEventListener('keydown',e=>{{if(e.key==='ArrowRight')show(i+1);if(e.key==='ArrowLeft')show(i-1)}});show(0);</script></body></html>'''
(DIST/'presentation.html').write_text(presentation)
(OUT/'speaking-outline.md').write_text('# Boston Building Energy Explorer: five-minute speaking outline\n\nTotal: 5:00. Timing includes the live filtering demonstration.\n\n'+'\n\n'.join('## '+s['time']+' | '+s['title']+'\n\n'+s['notes'] for s in slides)+'\n\nSources: '+m['source_url']+' and '+m['official_context_url'])
(OUT/'methodology.md').write_text('# Data & methodology\n\n'+'\n\n'.join('## '+t+'\n\n'+p for t,p in sections))
print('Created web methodology, one-page PDF, six presentation pages (300 seconds), English speaking outline, and reflection.')
